### ISSUE TITLE
Prompt Template for few-shot sentence-level translation. 

### ISSUE THREAD

**Issue by Romainpkq** [microsoft/gpt-MT#3]
I'm a bit confused about the Prompt Template for the few-shot sentence-level translation. Could you please give an example of the prompt template for the few-shot sentence-level translation? Thanks.

**Comment by AmrHendy** [comment]
Addressed in commit [89b2ffb](https://github.com/microsoft/gpt-MT/commit/89b2ffb89960de9f84717969f8654c1852c63f30).
